//------------------------------------------------------------------------------
// do not touch following lines...

// defines for node code template inclusions
{$UNDEF UNS_NodeBlank}
{$UNDEF UNS_NodeBool}
{$UNDEF UNS_NodeInt8}
{$UNDEF UNS_NodeUInt8}
{$UNDEF UNS_NodeInt16}
{$UNDEF UNS_NodeUInt16}
{$UNDEF UNS_NodeInt32}
{$UNDEF UNS_NodeUInt32}
{$UNDEF UNS_NodeInt64}
{$UNDEF UNS_NodeUInt64}
{$UNDEF UNS_NodeFloat32}
{$UNDEF UNS_NodeFloat64}
{$UNDEF UNS_NodeDateTime}
{$UNDEF UNS_NodeDate}
{$UNDEF UNS_NodeTime}
{$UNDEF UNS_NodeText}
{$UNDEF UNS_NodeBuffer}

{$UNDEF UNS_NodeAoBool}
{$UNDEF UNS_NodeAoInt8}
{$UNDEF UNS_NodeAoUInt8}
{$UNDEF UNS_NodeAoInt16}
{$UNDEF UNS_NodeAoUInt16}
{$UNDEF UNS_NodeAoInt32}
{$UNDEF UNS_NodeAoUInt32}
{$UNDEF UNS_NodeAoInt64}
{$UNDEF UNS_NodeAoUInt64}
{$UNDEF UNS_NodeAoFloat32}
{$UNDEF UNS_NodeAoFloat64}
{$UNDEF UNS_NodeAoDateTime}
{$UNDEF UNS_NodeAoDate}
{$UNDEF UNS_NodeAoTime}
{$UNDEF UNS_NodeAoText}
{$UNDEF UNS_NodeAoBuffer}
